name: PR Review
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

# Required permissions
permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: AI PR Review
        uses: jonit-dev/openrouter-github-action@main
        with:
          # Required inputs
          github_token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided
          open_router_key: ${{ secrets.OPEN_ROUTER_KEY }} # Must be set in repository secrets

          # Optional inputs with defaults
          model_id: 'deepseek/deepseek-chat:free' # Default model
          max_tokens: '2048' # Default max tokens

          # Optional custom prompt
          custom_prompt: |
            You are a security-focused reviewer. Analyze this PR with emphasis on:
            1. Data validation
            2. Input sanitization
            3. Best practices
            4. Bugs and Fix
            5. Adherence to existing security patterns and best practices
            
            Do not suggest new features or architectural changes. Focus strictly on the implementation as-is and how well it follows established standards.
            At the end, provide a 1–5 star rating based on overall code quality and security hygiene.